name: Test and Build Anchor

on:
  pull_request:
  push:
    branches: [ 'main' ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Jest (if missing)
        run: pnpm add jest --save-dev

      - name: Build the Anchor project
        run: pnpm run anchor build

      - name: Run tests
        run: pnpm run test

      - name: Deploy Anchor program
        run: anchor deploy
